DROP TABLE IF EXISTS TB_USERS;

CREATE TABLE TB_USERS
(
USERID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) ,
PASSWORD VARCHAR(50),
EMAILID VARCHAR(50),
SECURITYQUESTION INT,
SECURITYANSWER VARCHAR(50)
);

CREATE TABLE TB_EMPLOYEE
(
EMPLOYEEID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEENAME VARCHAR(50) ,
SKILLS VARCHAR(1000),
EXPERIENCE INT,
USERID INT,
FOREIGN KEY (USERID) REFERENCES TB_USERS(USERID)
);